### ISSUE TITLE
Usable in production?

### ISSUE THREAD

**Issue by joaoritter** [chainpoint/chainpoint-js#7]
How reliable is this project for use in a production system? Are there foreseeable associated costs?

**Comment by jacohend** [comment]
Chainpoint is ready for use in production. The network is reliable and the protocol is stable. Chainpoint-js automatically connects to a network of public gateways that can be used for free. Some organizations with certain security or scalability requirements choose to run private gateways. 

An overview of the network can be found at [Chainpoint Start](https://github.com/chainpoint/chainpoint-start)

**Comment by joaoritter** [comment]
Incredible, thanks! Given it's free, are you all looking for growth / traffic or are you just chillin and using this as a security lock for other projects you're working on?
